root = "."
tmp_dir = "tmp"

[build]
cmd = "make build"
bin = "./tmp/server"
full_bin = "ADDR=:8090 BASE_URL=http://localhost:8090 ./tmp/server"
include_ext = ["go", "templ", "md", "css", "js"]
exclude_dir = ["tmp", "node_modules", ".git"]
exclude_file = ["internal/templates/pages_templ.go"]
delay = 300
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true
